In [7]:
# explicitly require this experimental feature
from sklearn.experimental import enable_iterative_imputer  # noqa
# now you can import normally from sklearn.impute
from sklearn.impute import IterativeImputer
from sklearn.impute import SimpleImputer
import sklearn
import pandas as pd

In [11]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [17]:
raw_df

0      1      2    3      4      5     6       7    8      9   \
0       0.00632  18.00   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1     396.90000   4.98  24.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
2       0.02731   0.00   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
3     396.90000   9.14  21.60  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
4       0.02729   0.00   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
...         ...    ...    ...  ...    ...    ...   ...     ...  ...    ...   
1007  396.90000   5.64  23.90  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
1008    0.10959   0.00  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
1009  393.45000   6.48  22.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
1010    0.04741   0.00  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0   
1011  396.90000   7.88  11.90  NaN    NaN    NaN   NaN     NaN  NaN    NaN   

        10  
0     15.3  
1      NaN  
2     17.8  
3      NaN  
4     17.8  
...    ...  
1007   NaN  
1008  21.0  
1009   NaN  
1010  21.0  
1011   NaN  

[1012 rows x 11 columns]

## Data Imputation:

TL;DR: Fill the missing data.

In [112]:
# explicitly require this experimental feature
from sklearn.experimental import enable_iterative_imputer  # noqa
# now you can import normally from sklearn.impute
from sklearn.impute import IterativeImputer
# Importing the SimpleImputer class
from sklearn.impute import SimpleImputer
import numpy as np

In [118]:
data = [[12, np.nan, 34], [10, 32, np.nan],
        [np.nan, 11, 20]]

# TODO: replace this data with our data.

In [14]:
# Imputer object using the mean strategy and
# missing_values type for imputation
imputer = SimpleImputer(missing_values = np.nan,
                        strategy ='mean') 

In [119]:
# using iterativeImputer:
imputer = IterativeImputer(missing_values=np.nan)

In [120]:

print("Original Data : \n", data)
# Fitting the data to the imputer object
imputer = imputer.fit(data)
 
# Imputing the data    
data = imputer.transform(data)
 
print("Imputed Data : \n", data)

Original Data : 
 [[12, nan, 34], [10, 32, nan], [nan, 11, 20]]
Imputed Data : 
 [[12.         49.48349372 34.        ]
 [10.         32.         27.63963927]
 [ 7.59771988 11.         20.        ]]


## Regression:

Mapping all the features to regional market cap.

In [121]:
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF
import matplotlib.pyplot as plt


In [122]:
X_train = data[:2,:2]
Y_train = data[:2,2:3]
X_train

array([[12.        , 49.48349372],
       [10.        , 32.        ]])

In [123]:
X_test = data[2,:2]
Y_test = data[2,2:3]

X_test = np.expand_dims(X_test,1).T
Y_test = np.expand_dims(Y_test,1)

X_test.shape

(1, 2)

In [124]:

kernel = 1 * RBF(length_scale=1.0, length_scale_bounds=(1e-2, 1e2))
gaussian_process = GaussianProcessRegressor(kernel=kernel, n_restarts_optimizer=9)
gaussian_process.fit(X_train, Y_train)
gaussian_process.kernel_

31**2 * RBF(length_scale=85.3)

In [125]:
mean_prediction, std_prediction = gaussian_process.predict(X_test, return_std=True)

mean_prediction, std_prediction

(array([[18.92049385]]), array([2.36837146]))

### Plotting the Results

In [ ]:

# plt.plot(X_train, Y_train, label=r"$f(x) = x \sin(x)$", linestyle="dotted")
# # plt.scatter(X_train, Y_train, label="Observations")
# plt.plot(X, mean_prediction, label="Mean prediction")
# plt.fill_between(
#     X_train.ravel(),
#     mean_prediction - 1.96 * std_prediction,
#     mean_prediction + 1.96 * std_prediction,
#     alpha=0.5,
#     label=r"95% confidence interval",
# )
# plt.legend()
# plt.xlabel("$x$")
# plt.ylabel("$f(x)$")
# _ = plt.title("Gaussian process regression on noise-free dataset")